import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <nav style={{
          backgroundColor: '#333',
          padding: '10px 0',
          marginBottom: '20px',
          display: 'flex',
          justifyContent: 'center',
          gap: '20px',
        } as React.CSSProperties}>
          <a href="/" style={{ color: 'white', textDecoration: 'none', fontSize: 18 } as React.CSSProperties}>Home</a>
          <a href="/contact" style={{ color: 'white', textDecoration: 'none', fontSize: 18 } as React.CSSProperties}>Contact</a>
        </nav>
        {children}
      </body>
    </html>
  );
}
